### PR TITLE
Preparation as separate repository

### PR DESCRIPTION
**Pull request by HeikoKlare**
The projects in this repository have been moved from the https://github.com/vitruv-tools/Vitruv repository. The history of the projects has been extracted from that repository. This PR adds all the infrastructure for the repository, consisting of Maven build specification, a new feature, update site specification, readme and CI. In addition, it renames the projects from `tools.vitruv.domains.*` to `tools.vitruv.adapters.*`.

### CODE REVIEW

**Comment by JanWittler** [comment]
The naming is pretty confusing as we already have a `View` concept.
The moved projects are the Eclipse-dependent projects right? So maybe we go in that direction with the naming? `Vitruv-Eclipse-Adapters`?

**Comment by HeikoKlare** [comment]
Do you mean the name of the repository or the name of some project? The repository is not tied to Eclipse, but is supposed to provide tool adapter for views. Maybe we should make that explicit?

**Comment by JanWittler** [comment]
Of the repository itself. From the name `Vitruv-Views`, I would expect the view framework, i.e. `tools.vitruv.framework.views` (but they should stay where they are right now 😄).

**Comment by HeikoKlare** [comment]
That's true. Then what about `Vitruv-Tool-Adapters`? And `tools.vitruv.adapters.*` or something like that as the project and package namespaces?

**Comment by HeikoKlare** [comment]
Thanks for pointing that out, @JanWittler. Naming makes much more sense now.

**Review by JanWittler — APPROVED** [review]

**Pull request merged**
